In [1]:
import numpy as np
np.__version__

'2.3.5'

In [ ]:
import sys 
sys.version


'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
print("hello world")


hello world


In [4]:
print('this id my python jurney started with python 3.111')

this id my python jurney started with python 3.111


In [ ]:
mylist=[1,2,3,3,4,5,6,7,8,9,10]
mylist

type(mylist)


list

In [12]:
arr=np.array(mylist)
arr

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])