In [4]:
import numpy as np
np.__version__

'2.3.5'

In [6]:
import sys 
sys.version


'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
print("hello world")


hello world


In [4]:
print('this id my python jurney started with python 3.111')

this id my python jurney started with python 3.111


In [ ]:
mylist=[1,2,3,3,4,5,6,7,8,9,10]
mylist

type(mylist)


list

In [12]:
arr=np.array(mylist)
arr

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# Images

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os
from PIL import Image

img = r"C:/Users/Pramod/OneDrive/AI Python/Senapati Sir/Document/img"

img

img_ar=np.asarray(img)
img_ar




array('C:/Users/Pramod/OneDrive/AI Python/Senapati Sir/Document/img',
      dtype='<U60')

In [7]:
np.__version__

'2.3.5'

In [9]:
s=['sas',212,212,'demo']

arr=np.array(s)

for i in arr:
    print(i)

sas
212
212
demo


In [11]:
type(arr)

arr

array(['sas', '212', '212', 'demo'], dtype='<U21')

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
np.arange(20,10)
np.arange(-10,20)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [17]:
np.arange(-16,20)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange(-20,-9)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10])

In [20]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
np.arange(10,10)

array([], dtype=int64)

In [22]:
np.arange()

TypeError: arange() requires stop to be specified.

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [29]:
np.arange(10,dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
d=np.zeros([2,2])
print(d)
print(type(d))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
n=(1,2)
n1=(23,23)
n1
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [39]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
np.ones(3)

array([1., 1., 1.])

In [46]:
np.ones((4,4), dtype=int) 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
rand(20)

NameError: name 'rand' is not defined

In [49]:
random.rand(3,2)

NameError: name 'random' is not defined

In [50]:
np.random.rand(5)

array([0.83735969, 0.36782818, 0.43323897, 0.46000911, 0.40195373])

In [51]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [52]:
np.random.rand(20)

array([0.11260052, 0.24909777, 0.70341484, 0.74172263, 0.3330264 ,
       0.27113709, 0.9369846 , 0.89919903, 0.0803887 , 0.63581405,
       0.83655698, 0.18118146, 0.09321155, 0.51577943, 0.83981961,
       0.59211203, 0.69316011, 0.9038818 , 0.58571338, 0.66407748])

In [55]:
np.random.random_integers(20)

C:\Users\Pramod\AppData\Local\Temp\ipykernel_18616\1590996773.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 20 + 1) instead
  np.random.random_integers(20)


np.int32(17)